package com.someone.util;

import android.annotation.SuppressLint;
import android.content.res.AssetManager;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PixelFormat;
import android.graphics.RectF;
import android.graphics.drawable.Drawable;
import androidx.annotation.NonNull;
import androidx.core.graphics.PathParser;
import com.someone.debug.LogReceiver;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @Author Someone
 * @Date 2024/09/11 07:17
 */
public class VectorDrawable extends Drawable {
    private Path[] path;
    private String[] pathData;
    private Paint[] paint;
    private Paint[] strokePaint;
    private int width = -2;
    private int height = -2;
    private boolean keepAspectRatio = false;
    private RectF bounds;
    private boolean isDraw = false;

    public VectorDrawable(String[] path, int[] paintColor, Paint.Style[] style, int[] strokeColor , int[] strokeWidth) {
        init(path, paintColor, style, strokeColor, strokeWidth);
    }

    public VectorDrawable(String[] path, int paintColor, Paint.Style style, int strokeColor, int strokeWidth) {
        init(path, new int[]{paintColor}, new Paint.Style[]{style}, new int[]{strokeColor}, new int[]{strokeWidth});
    }

    public VectorDrawable(String[] path, int[] paintColor, Paint.Style[] style) {
        init(path, paintColor, style, null, null);
    }

    public VectorDrawable(String[] path, int paintColor, Paint.Style style) {
        init(path, new int[]{paintColor}, new Paint.Style[]{style}, null, null);
    }

    public VectorDrawable(String path, int paintColor, Paint.Style style, int strokeColor, int strokeWidth) {
        init(new String[]{path}, new int[]{paintColor}, new Paint.Style[]{style}, new int[]{strokeColor}, new int[]{strokeWidth});
    }

    public VectorDrawable(String path, int paintColor, Paint.Style style) {
        init(new String[]{path}, new int[]{paintColor}, new Paint.Style[]{style}, null , null);
    }

    public void init(String[] path, int[] paintColor, Paint.Style[] style , int[] strokeColor, int[] strokeWidth) {
        if (paintColor.length != 1 && paintColor.length != pathData.length) {
            throw new IllegalArgumentException(
                "paintColor length must be 1 or equal to pathData length"
            );
        }
        if (style.length != 1 && style.length != pathData.length) {
            throw new IllegalArgumentException(
                "style length must be 1 or equal to pathData length"
            );
        }
        if (path == null) {
            throw new IllegalArgumentException("vectorPath is null");
        }
        if (path.length == 0) {
            throw new IllegalArgumentException("vectorPathArray length is 0");
        }
        if (paintColor.length == 0) {
            throw new IllegalArgumentException("paintColorArray length is 0");
        }
        if (style.length == 0) {
            throw new IllegalArgumentException("styleArray length is 0");
        }
        this.pathData = path;
        this.paint = new Paint[pathData.length];
        if (strokeColor != null && strokeWidth != null && strokeColor.length != 0 && strokeWidth.length != 0 && strokeColor.length == strokeWidth.length) {
            strokePaint = new Paint[pathData.length];
        }
        for (int i = 0; i < pathData.length; i++) {
            paint[i] = new Paint();
            if (strokePaint != null) {
                strokePaint[i] = new Paint();
            }
            paint[i].setColor(paintColor.length > i ? paintColor[i] : paintColor[0]);
            Paint.Style currentStyle = style.length > i ? style[i] : style[0];
            paint[i].setStyle(currentStyle);
            if (currentStyle == Paint.Style.FILL_AND_STROKE && strokePaint != null) {
                strokePaint[i].setStyle(Paint.Style.STROKE);
                if (strokeColor != null) {
                    strokePaint[i].setColor(strokeColor.length > i ? strokeColor[i] : strokeColor[0]);
                }
                if (strokeWidth != null) {
                    strokePaint[i].setStrokeWidth(strokeWidth.length > i ? strokeWidth[i] : strokeWidth[0]);
                }
            }
        }
    }

    public VectorDrawable setSize(int width, int height) {
        this.width = width;
        this.height = height;
        return this;
    }

    public VectorDrawable setKeepAspectRatio(boolean keepAspectRatio) {
        this.keepAspectRatio = keepAspectRatio;
        return this;
    }

    public Path[] getPath(int width, int height) {
        Path path = new Path();
        Path[] pathArray = new Path[pathData.length];
        for (int i = 0; i < pathData.length; i++) {
            pathArray[i] = new Path();
            PathParser.PathDataNode[] nodes = PathParser.createNodesFromPathData(pathData[i]);
            PathParser.PathDataNode.nodesToPath(nodes, pathArray[i]);
            path.addPath(pathArray[i]);
        }
        RectF bounds = new RectF();
        path.computeBounds(bounds, true);
        if (strokePaint != null && strokePaint.length != 0) {
            float strokePadding = 0f;
            for (Paint p : strokePaint) {
                if (p != null) {
                    strokePadding = Math.max(strokePadding, p.getStrokeWidth() / 2f);
                }
            }
            bounds.inset(-strokePadding, -strokePadding);
        }
        float scaleX;
        float scaleY;
        scaleX = this.width == -2 ? 1f : ((float) this.width > 0 ? this.width : width) / bounds.width();
        scaleY = this.height == -2 ? 1f : ((float) this.height > 0 ? this.height : height) / bounds.height();
        float scale = keepAspectRatio ? Math.min(scaleX, scaleY) : 1f;
        Matrix matrix = new Matrix();
        if (keepAspectRatio) {
            // 保持宽高比
            matrix.postScale(scale, scale);
        } else {
            // 不保持宽高比，分别缩放
            matrix.postScale(scaleX, scaleY);
        }
        for (int i = 0; i < pathArray.length; i++) {
            Path scaledPath = new Path();
            scaledPath.addPath(pathArray[i]);
            scaledPath.transform(matrix);
            pathArray[i] = scaledPath;
        }
        return pathArray;
    }

    @SuppressLint("CanvasSize")
    @Override
    public void draw(@NonNull Canvas canvas) {
        if (!isDraw) {
            this.path = getPath(canvas.getWidth(), canvas.getHeight());
            // 计算所有路径的整体边界
            RectF totalBounds = new RectF();
            for (Path p : path) {
                RectF pathBounds = new RectF();
                p.computeBounds(pathBounds, true);
                totalBounds.union(pathBounds);
            }
            this.bounds = totalBounds;
            isDraw = true;
        }
        float centerX = canvas.getWidth() / 2f;
        float centerY = canvas.getHeight() / 2f;
        float pathCenterX = bounds.centerX();
        float pathCenterY = bounds.centerY();
        float translateX = centerX - pathCenterX;
        float translateY = centerY - pathCenterY;
        canvas.save();
        canvas.translate(translateX, translateY); // 整体平移
        for (int i = 0; i < path.length; i++) {
            canvas.drawPath(path[i], paint[i]);
            if (strokePaint != null) {
                strokePaint[i].setStyle(Paint.Style.STROKE);
                canvas.drawPath(path[i], strokePaint[i]);
            }
        }
        canvas.restore(); // 恢复画布状态
    }

    @Override
    public void setBounds(int left, int top, int right, int bottom) {
        super.setBounds(left, top, right, bottom);
        // 确保边界框是正方形，以便居中显示
        int width = right - left;
        int height = bottom - top;
        int size = Math.min(width, height);
        super.setBounds(left, top, left + size, top + size);
    }

    @Override
    public void setAlpha(int alpha) {
        for (Paint value : paint) {
            value.setAlpha(alpha);
        }
    }

    @Override
    public void setColorFilter(ColorFilter colorFilter) {
        for (Paint value : paint) {
            value.setColorFilter(colorFilter);
        }
    }

    @Override
    public int getOpacity() {
        return PixelFormat.TRANSLUCENT;
    }

    public final enum StyleType {
        FILLED,
        OUTLINED,
        ROUND,
        SHARP,
        TWOTONE
        }

    public final enum VectorPath {
        _3D_ROTATION,
        ACCESSIBILITY,
        ACCESSIBILITY_NEW,
        ACCESSIBLE,
        ACCESSIBLE_FORWARD,
        ACCOUNT_BALANCE,
        ACCOUNT_BALANCE_WALLET,
        ACCOUNT_BOX,
        ACCOUNT_CIRCLE,
        ADD_SHOPPING_CART,
        ADD_TASK,
        ADD_TO_DRIVE,
        ADDCHART,
        ADMIN_PANEL_SETTINGS,
        ALARM,
        ALARM_ADD,
        ALARM_OFF,
        ALARM_ON,
        ALL_INBOX,
        ALL_OUT,
        ANALYTICS,
        ANCHOR,
        ANDROID,
        ANNOUNCEMENT,
        API,
        APP_BLOCKING,
        ARROW_CIRCLE_DOWN,
        ARROW_CIRCLE_UP,
        ARROW_RIGHT_ALT,
        ARTICLE,
        ASPECT_RATIO,
        ASSESSMENT,
        ASSIGNMENT,
        ASSIGNMENT_IND,
        ASSIGNMENT_LATE,
        ASSIGNMENT_RETURN,
        ASSIGNMENT_RETURNED,
        ASSIGNMENT_TURNED_IN,
        AUTORENEW,
        BACKUP,
        BACKUP_TABLE,
        BATCH_PREDICTION,
        BOOK,
        BOOK_ONLINE,
        BOOKMARK,
        BOOKMARK_BORDER,
        BOOKMARKS,
        BUG_REPORT,
        BUILD,
        BUILD_CIRCLE,
        CACHED,
        CALENDAR_TODAY,
        CALENDAR_VIEW_DAY,
        CAMERA_ENHANCE,
        CANCEL_SCHEDULE_SEND,
        CARD_GIFTCARD,
        CARD_MEMBERSHIP,
        CARD_TRAVEL,
        CHANGE_HISTORY,
        CHECK_CIRCLE,
        CHECK_CIRCLE_OUTLINE,
        CHROME_READER_MODE,
        CIRCLE_NOTIFICATIONS,
        CLASS,
        CLOSE_FULLSCREEN,
        CODE,
        COMMENT_BANK,
        COMMUTE,
        COMPARE_ARROWS,
        COMPRESS,
        CONTACT_PAGE,
        CONTACT_SUPPORT,
        CONTACTLESS,
        COPYRIGHT,
        CREDIT_CARD,
        DANGEROUS,
        DASHBOARD,
        DASHBOARD_CUSTOMIZE,
        DATE_RANGE,
        DELETE,
        DELETE_FOREVER,
        DELETE_OUTLINE,
        DESCRIPTION,
        DISABLED_BY_DEFAULT,
        DNS,
        DONE,
        DONE_ALL,
        DONE_OUTLINE,
        DONUT_LARGE,
        DONUT_SMALL,
        DRAG_INDICATOR,
        DYNAMIC_FORM,
        ECO,
        EDIT_OFF,
        EJECT,
        EURO_SYMBOL,
        EVENT,
        EVENT_SEAT,
        EXIT_TO_APP,
        EXPAND,
        EXPLORE,
        EXPLORE_OFF,
        EXTENSION,
        FACE,
        FACE_UNLOCK,
        FACT_CHECK,
        FAVORITE,
        FAVORITE_BORDER,
        FEEDBACK,
        FILE_PRESENT,
        FILTER_ALT,
        FILTER_LIST_ALT,
        FIND_IN_PAGE,
        FIND_REPLACE,
        FINGERPRINT,
        FIT_SCREEN,
        FLAKY,
        FLIGHT_LAND,
        FLIGHT_TAKEOFF,
        FLIP_TO_BACK,
        FLIP_TO_FRONT,
        G_TRANSLATE,
        GAVEL,
        GET_APP,
        GIF,
        GRADE,
        GRADING,
        GROUP_WORK,
        HELP,
        HELP_CENTER,
        HELP_OUTLINE,
        HIGHLIGHT_ALT,
        HIGHLIGHT_OFF,
        HISTORY,
        HISTORY_TOGGLE_OFF,
        HOME,
        HOME_FILLED,
        HORIZONTAL_SPLIT,
        HOURGLASS_DISABLED,
        HOURGLASS_EMPTY,
        HOURGLASS_FULL,
        HTTP,
        HTTPS,
        IMPORTANT_DEVICES,
        INFO,
        INFO_OUTLINE,
        INPUT,
        INTEGRATION_INSTRUCTIONS,
        INVERT_COLORS,
        LABEL,
        LABEL_IMPORTANT,
        LABEL_IMPORTANT_OUTLINE,
        LABEL_OFF,
        LABEL_OUTLINE,
        LANGUAGE,
        LAUNCH,
        LEADERBOARD,
        LIGHTBULB,
        LIGHTBULB_OUTLINE,
        LINE_STYLE,
        LINE_WEIGHT,
        LIST,
        LOCK,
        LOCK_CLOCK,
        LOCK_OPEN,
        LOCK_OUTLINE,
        LOGIN,
        LOGOUT,
        LOYALTY,
        MARK_AS_UNREAD,
        MARKUNREAD_MAILBOX,
        MAXIMIZE,
        MEDIATION,
        MINIMIZE,
        MODEL_TRAINING,
        NEXT_PLAN,
        NIGHTLIGHT_ROUND,
        NOT_ACCESSIBLE,
        NOT_STARTED,
        NOTE_ADD,
        OFFLINE_BOLT,
        OFFLINE_PIN,
        ONLINE_PREDICTION,
        OPACITY,
        OPEN_IN_BROWSER,
        OPEN_IN_FULL,
        OPEN_IN_NEW,
        OPEN_WITH,
        OUTBOND,
        OUTBOX,
        OUTGOING_MAIL,
        OUTLET,
        PAGEVIEW,
        PAN_TOOL,
        PAYMENT,
        PENDING,
        PENDING_ACTIONS,
        PERM_CAMERA_MIC,
        PERM_CONTACT_CALENDAR,
        PERM_DATA_SETTING,
        PERM_IDENTITY,
        PERM_MEDIA,
        PERM_PHONE_MSG,
        PERM_SCAN_WIFI,
        PICTURE_IN_PICTURE,
        PLAGIARISM,
        POLYMER,
        POWER_SETTINGS_NEW,
        PREGNANT_WOMAN,
        PREVIEW,
        PRINT,
        QUESTION_ANSWER,
        RECEIPT,
        REDEEM,
        REMOVE_SHOPPING_CART,
        REORDER,
        REQUEST_PAGE,
        RESTORE,
        RULE,
        SCHEDULE,
        SCHEDULE_SEND,
        SEARCH,
        SEND_AND_ARCHIVE,
        SETTINGS,
        SETTINGS_APPLICATIONS,
        SETTINGS_BACKUP_RESTORE,
        SETTINGS_BLUETOOTH,
        SETTINGS_CELL,
        SETTINGS_INPUT_HDMI,
        SETTINGS_INPUT_SVIDEO,
        SETTINGS_REMOTE,
        SHOP,
        SHOPPING_BAG,
        SHOPPING_BASKET,
        SHOPPING_CART,
        SOURCE,
        SPEAKER_NOTES_OFF,
        SPELLCHECK,
        STARS,
        STICKY_NOTE_2,
        SUBTITLES_OFF,
        SWAP_HORIZ,
        SWAP_VERT,
        SWIPE,
        SYSTEM_UPDATE_ALT,
        TABLE_VIEW,
        TEXT_ROTATE_VERTICAL,
        TEXT_ROTATION_NONE,
        THEATERS,
        THUMB_DOWN,
        THUMB_UP,
        THUMB_UP_OFF_ALT,
        THUMBS_UP_DOWN,
        TIMELINE,
        TOLL,
        TOUCH_APP,
        TRACK_CHANGES,
        TRANSLATE,
        TRENDING_DOWN,
        TRENDING_FLAT,
        TURNED_IN_NOT,
        UNPUBLISHED,
        UPDATE,
        VERIFIED_USER,
        VIEW_COLUMN,
        VIEW_HEADLINE,
        VIEW_LIST,
        VIEW_MODULE,
        VIEW_QUILT,
        VIEW_SIDEBAR,
        VIEW_STREAM,
        VISIBILITY,
        VISIBILITY_OFF,
        VOICE_OVER_OFF,
        WATCH_LATER,
        WORK_OFF,
        YOUTUBE_SEARCHED_FOR,
        PERM_DEVICE_INFORMATION,
        PETS,
        PICTURE_IN_PICTURE_ALT,
        PLAY_FOR_WORK,
        PRIVACY_TIP,
        PUBLISHED_WITH_CHANGES,
        QUERY_BUILDER,
        QUICKREPLY,
        RECORD_VOICE_OVER,
        REMOVE_DONE,
        REPORT_PROBLEM,
        RESTORE_FROM_TRASH,
        RESTORE_PAGE,
        ROOM,
        ROUNDED_CORNER,
        ROWING,
        SAVED_SEARCH,
        SEARCH_OFF,
        SEGMENT,
        SETTINGS_BRIGHTNESS,
        SETTINGS_ETHERNET,
        SETTINGS_INPUT_ANTENNA,
        SETTINGS_INPUT_COMPONENT,
        SETTINGS_INPUT_COMPOSITE,
        SETTINGS_OVERSCAN,
        SETTINGS_PHONE,
        SETTINGS_POWER,
        SETTINGS_VOICE,
        SHOP_TWO,
        SMART_BUTTON,
        SPEAKER_NOTES,
        STAR_RATE,
        STORE,
        SUBJECT,
        SUPERVISED_USER_CIRCLE,
        SUPERVISOR_ACCOUNT,
        SUPPORT,
        SWAP_HORIZONTAL_CIRCLE,
        SWAP_VERTICAL_CIRCLE,
        SYNC_ALT,
        TAB,
        TAB_UNSELECTED,
        TEXT_ROTATE_UP,
        TEXT_ROTATION_ANGLEDOWN,
        TEXT_ROTATION_ANGLEUP,
        TEXT_ROTATION_DOWN,
        THUMB_DOWN_OFF_ALT,
        TOC,
        TODAY,
        TOUR,
        TRENDING_UP,
        TURNED_IN,
        UPGRADE,
        VERIFIED,
        VERTICAL_SPLIT,
        VIEW_AGENDA,
        VIEW_ARRAY,
        VIEW_CAROUSEL,
        VIEW_DAY,
        VIEW_IN_AR,
        VIEW_WEEK,
        WIFI_PROTECTED_SETUP,
        WORK,
        WORK_OUTLINE,
        WYSIWYG,
        ZOOM_IN,
        ZOOM_OUT,
        ADD_ALERT,
        AUTO_DELETE,
        ERROR,
        ERROR_OUTLINE,
        NOTIFICATION_IMPORTANT,
        WARNING,
        WARNING_AMBER,
        _10K,
        _1K,
        _1K_PLUS,
        _2K,
        _2K_PLUS,
        _3K,
        _3K_PLUS,
        _4K,
        _4K_PLUS,
        _5G,
        _5K,
        _5K_PLUS,
        _6K,
        _6K_PLUS,
        _7K,
        _7K_PLUS,
        _8K,
        _8K_PLUS,
        _9K,
        _9K_PLUS,
        ADD_TO_QUEUE,
        AIRPLAY,
        ALBUM,
        ART_TRACK,
        AV_TIMER,
        BRANDING_WATERMARK,
        CALL_TO_ACTION,
        CLOSED_CAPTION,
        CLOSED_CAPTION_DISABLED,
        CLOSED_CAPTION_OFF,
        CONTROL_CAMERA,
        EQUALIZER,
        EXPLICIT,
        FAST_FORWARD,
        FAST_REWIND,
        FEATURED_PLAY_LIST,
        FEATURED_VIDEO,
        FIBER_DVR,
        FIBER_MANUAL_RECORD,
        FIBER_NEW,
        FIBER_PIN,
        FIBER_SMART_RECORD,
        FORWARD_10,
        FORWARD_30,
        FORWARD_5,
        GAMES,
        HD,
        HEARING,
        HEARING_DISABLED,
        HIGH_QUALITY,
        LIBRARY_ADD,
        LIBRARY_ADD_CHECK,
        LIBRARY_BOOKS,
        LIBRARY_MUSIC,
        LOOP,
        MIC,
        MIC_NONE,
        MIC_OFF,
        MISSED_VIDEO_CALL,
        MOVIE,
        MUSIC_VIDEO,
        NEW_RELEASES,
        NOT_INTERESTED,
        NOTE,
        PAUSE,
        PAUSE_CIRCLE_FILLED,
        PAUSE_CIRCLE_OUTLINE,
        PLAY_ARROW,
        PLAY_CIRCLE_FILLED,
        PLAY_CIRCLE_OUTLINE,
        PLAY_DISABLED,
        PLAYLIST_ADD,
        PLAYLIST_ADD_CHECK,
        PLAYLIST_PLAY,
        QUEUE,
        QUEUE_MUSIC,
        QUEUE_PLAY_NEXT,
        RADIO,
        RECENT_ACTORS,
        REMOVE_FROM_QUEUE,
        REPEAT,
        REPEAT_ON,
        REPEAT_ONE,
        REPEAT_ONE_ON,
        REPLAY,
        REPLAY_10,
        REPLAY_30,
        REPLAY_5,
        REPLAY_CIRCLE_FILLED,
        SD,
        SHUFFLE,
        SHUFFLE_ON,
        SKIP_NEXT,
        SKIP_PREVIOUS,
        SLOW_MOTION_VIDEO,
        SNOOZE,
        SORT_BY_ALPHA,
        SPEED,
        STOP,
        STOP_CIRCLE,
        SUBSCRIPTIONS,
        SUBTITLES,
        SURROUND_SOUND,
        VIDEO_CALL,
        VIDEO_LABEL,
        VIDEO_LIBRARY,
        VIDEO_SETTINGS,
        VIDEOCAM,
        VIDEOCAM_OFF,
        VOLUME_DOWN,
        VOLUME_MUTE,
        VOLUME_OFF,
        VOLUME_UP,
        WEB,
        WEB_ASSET,
        ADD_IC_CALL,
        ALTERNATE_EMAIL,
        APP_REGISTRATION,
        BUSINESS,
        CALL,
        CALL_END,
        CALL_MADE,
        CALL_MERGE,
        CALL_MISSED,
        CALL_MISSED_OUTGOING,
        CALL_RECEIVED,
        CALL_SPLIT,
        CANCEL_PRESENTATION,
        CELL_WIFI,
        CHAT,
        CHAT_BUBBLE,
        CHAT_BUBBLE_OUTLINE,
        CLEAR_ALL,
        COMMENT,
        CONTACT_MAIL,
        CONTACT_PHONE,
        CONTACTS,
        DESKTOP_ACCESS_DISABLED,
        DIALER_SIP,
        DIALPAD,
        DOMAIN_DISABLED,
        DOMAIN_VERIFICATION,
        DUO,
        EMAIL,
        FORUM,
        FORWARD_TO_INBOX,
        HOURGLASS_BOTTOM,
        HOURGLASS_TOP,
        IMPORT_CONTACTS,
        IMPORT_EXPORT,
        INVERT_COLORS_OFF,
        LIST_ALT,
        LIVE_HELP,
        LOCATION_OFF,
        LOCATION_ON,
        MAIL_OUTLINE,
        MARK_CHAT_READ,
        MARK_CHAT_UNREAD,
        MARK_EMAIL_READ,
        MARK_EMAIL_UNREAD,
        MESSAGE,
        MOBILE_SCREEN_SHARE,
        MORE_TIME,
        NAT,
        NO_SIM,
        PAUSE_PRESENTATION,
        PERSON_ADD_DISABLED,
        PERSON_SEARCH,
        PHONE,
        PHONE_DISABLED,
        PHONE_ENABLED,
        PHONELINK_ERASE,
        PHONELINK_LOCK,
        PHONELINK_RING,
        PHONELINK_SETUP,
        PORTABLE_WIFI_OFF,
        PRESENT_TO_ALL,
        PRINT_DISABLED,
        QR_CODE,
        QR_CODE_SCANNER,
        READ_MORE,
        RING_VOLUME,
        RSS_FEED,
        RTT,
        SCREEN_SHARE,
        SENTIMENT_SATISFIED_ALT,
        SPEAKER_PHONE,
        STAY_CURRENT_LANDSCAPE,
        STAY_CURRENT_PORTRAIT,
        STAY_PRIMARY_LANDSCAPE,
        STAY_PRIMARY_PORTRAIT,
        STOP_SCREEN_SHARE,
        SWAP_CALLS,
        TEXTSMS,
        UNSUBSCRIBE,
        VOICEMAIL,
        VPN_KEY,
        WIFI_CALLING,
        ADD,
        ADD_BOX,
        ADD_CIRCLE,
        ADD_CIRCLE_OUTLINE,
        ADD_LINK,
        AMP_STORIES,
        ARCHIVE,
        ATTRIBUTION,
        BACKSPACE,
        BALLOT,
        BIOTECH,
        BLOCK,
        BLOCK_FLIPPED,
        BOLT,
        CALCULATE,
        CLEAR,
        CONTENT_COPY,
        CONTENT_CUT,
        CONTENT_PASTE,
        CREATE,
        DELETE_SWEEP,
        DRAFTS,
        DYNAMIC_FEED,
        FILE_COPY,
        FILTER_LIST,
        FLAG,
        FONT_DOWNLOAD,
        FORWARD,
        GESTURE,
        HOW_TO_REG,
        HOW_TO_VOTE,
        INBOX,
        INSIGHTS,
        INVENTORY,
        LINK,
        LINK_OFF,
        LOW_PRIORITY,
        MAIL,
        MARKUNREAD,
        MOVE_TO_INBOX,
        NEXT_WEEK,
        OUTLINED_FLAG,
        POLICY,
        PUSH_PIN,
        REDO,
        REMOVE,
        REMOVE_CIRCLE,
        REMOVE_CIRCLE_OUTLINE,
        REPLY,
        REPLY_ALL,
        REPORT,
        REPORT_GMAILERRORRED,
        REPORT_OFF,
        SAVE,
        SAVE_ALT,
        SELECT_ALL,
        SEND,
        SHIELD,
        SORT,
        SQUARE_FOOT,
        STACKED_BAR_CHART,
        STREAM,
        TAG,
        TEXT_FORMAT,
        UNARCHIVE,
        UNDO,
        WAVES,
        WEEKEND,
        WHERE_TO_VOTE,
        ACCESS_ALARM,
        ACCESS_ALARMS,
        ACCESS_TIME,
        AD_UNITS,
        ADD_ALARM,
        ADD_TO_HOME_SCREEN,
        AIRPLANEMODE_ACTIVE,
        AIRPLANEMODE_INACTIVE,
        BATTERY_20,
        BATTERY_30,
        BATTERY_50,
        BATTERY_60,
        BATTERY_80,
        BATTERY_90,
        BATTERY_ALERT,
        BATTERY_CHARGING_20,
        BATTERY_CHARGING_30,
        BATTERY_CHARGING_50,
        BATTERY_CHARGING_60,
        BATTERY_CHARGING_80,
        BATTERY_CHARGING_90,
        BATTERY_CHARGING_FULL,
        BATTERY_FULL,
        BATTERY_STD,
        BATTERY_UNKNOWN,
        BLUETOOTH,
        BLUETOOTH_CONNECTED,
        BLUETOOTH_DISABLED,
        BLUETOOTH_SEARCHING,
        BRIGHTNESS_AUTO,
        BRIGHTNESS_HIGH,
        BRIGHTNESS_LOW,
        BRIGHTNESS_MEDIUM,
        DATA_USAGE,
        DEVELOPER_MODE,
        DEVICE_THERMOSTAT,
        DEVICES,
        DVR,
        GPS_FIXED,
        GPS_NOT_FIXED,
        GPS_OFF,
        GRAPHIC_EQ,
        LOCATION_DISABLED,
        LOCATION_SEARCHING,
        MOBILE_FRIENDLY,
        MOBILE_OFF,
        NETWORK_CELL,
        NETWORK_WIFI,
        NFC,
        RESET_TV,
        SCREEN_LOCK_LANDSCAPE,
        SCREEN_LOCK_PORTRAIT,
        SCREEN_LOCK_ROTATION,
        SCREEN_ROTATION,
        SCREEN_SEARCH_DESKTOP,
        SD_STORAGE,
        SEND_TO_MOBILE,
        SETTINGS_SYSTEM_DAYDREAM,
        SIGNAL_CELLULAR_0_BAR,
        SIGNAL_CELLULAR_1_BAR,
        SIGNAL_CELLULAR_2_BAR,
        SIGNAL_CELLULAR_3_BAR,
        SIGNAL_CELLULAR_4_BAR,
        SIGNAL_CELLULAR_ALT,
        SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_0_BAR,
        SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_1_BAR,
        SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_2_BAR,
        SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_3_BAR,
        SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR,
        SIGNAL_CELLULAR_NO_SIM,
        SIGNAL_CELLULAR_NULL,
        SIGNAL_CELLULAR_OFF,
        SIGNAL_WIFI_0_BAR,
        SIGNAL_WIFI_1_BAR,
        SIGNAL_WIFI_1_BAR_LOCK,
        SIGNAL_WIFI_2_BAR,
        SIGNAL_WIFI_2_BAR_LOCK,
        SIGNAL_WIFI_OFF,
        SIGNAL_WIFI_3_BAR,
        SIGNAL_WIFI_3_BAR_LOCK,
        SIGNAL_WIFI_4_BAR,
        SIGNAL_WIFI_4_BAR_LOCK,
        STORAGE,
        THERMOSTAT,
        USB,
        WALLPAPER,
        WIDGETS,
        WIFI_LOCK,
        WIFI_TETHERING,
        ADD_CHART,
        ADD_COMMENT,
        ATTACH_FILE,
        ATTACH_MONEY,
        BAR_CHART,
        BORDER_ALL,
        BORDER_BOTTOM,
        BORDER_CLEAR,
        BORDER_COLOR,
        BORDER_HORIZONTAL,
        BORDER_INNER,
        BORDER_LEFT,
        BORDER_OUTER,
        BORDER_RIGHT,
        BORDER_STYLE,
        BORDER_TOP,
        BORDER_VERTICAL,
        BUBBLE_CHART,
        DRAG_HANDLE,
        FORMAT_ALIGN_CENTER,
        FORMAT_ALIGN_JUSTIFY,
        FORMAT_ALIGN_LEFT,
        FORMAT_ALIGN_RIGHT,
        FORMAT_BOLD,
        FORMAT_CLEAR,
        FORMAT_COLOR_FILL,
        FORMAT_COLOR_RESET,
        FORMAT_COLOR_TEXT,
        FORMAT_INDENT_DECREASE,
        FORMAT_INDENT_INCREASE,
        FORMAT_ITALIC,
        FORMAT_LINE_SPACING,
        FORMAT_LIST_BULLETED,
        FORMAT_LIST_NUMBERED,
        FORMAT_LIST_NUMBERED_RTL,
        FORMAT_PAINT,
        FORMAT_QUOTE,
        FORMAT_SHAPES,
        FORMAT_SIZE,
        FORMAT_STRIKETHROUGH,
        FORMAT_TEXTDIRECTION_L_TO_R,
        FORMAT_TEXTDIRECTION_R_TO_L,
        FORMAT_UNDERLINED,
        FUNCTIONS,
        HEIGHT,
        HIGHLIGHT,
        HORIZONTAL_RULE,
        INSERT_CHART,
        INSERT_CHART_OUTLINED,
        INSERT_COMMENT,
        INSERT_DRIVE_FILE,
        INSERT_EMOTICON,
        INSERT_INVITATION,
        INSERT_LINK,
        INSERT_PHOTO,
        LINEAR_SCALE,
        MARGIN,
        MERGE_TYPE,
        MODE,
        MODE_COMMENT,
        MODE_EDIT,
        MONETIZATION_ON,
        MONEY_OFF,
        MONEY_OFF_CSRED,
        MULTILINE_CHART,
        NOTES,
        PADDING,
        PIE_CHART,
        PIE_CHART_OUTLINE,
        PIE_CHART_OUTLINED,
        POST_ADD,
        PUBLISH,
        SCATTER_PLOT,
        SCORE,
        SHORT_TEXT,
        SHOW_CHART,
        SPACE_BAR,
        STACKED_LINE_CHART,
        STRIKETHROUGH_S,
        SUBSCRIPT,
        SUPERSCRIPT,
        TABLE_CHART,
        TABLE_ROWS,
        TEXT_FIELDS,
        TITLE,
        VERTICAL_ALIGN_BOTTOM,
        VERTICAL_ALIGN_CENTER,
        VERTICAL_ALIGN_TOP,
        WRAP_TEXT,
        APPROVAL,
        ATTACH_EMAIL,
        ATTACHMENT,
        CLOUD,
        CLOUD_CIRCLE,
        CLOUD_DONE,
        CLOUD_DOWNLOAD,
        CLOUD_OFF,
        CLOUD_QUEUE,
        CLOUD_UPLOAD,
        CREATE_NEW_FOLDER,
        DOWNLOAD,
        DOWNLOAD_DONE,
        DRIVE_FILE_MOVE,
        DRIVE_FILE_MOVE_OUTLINE,
        DRIVE_FILE_RENAME_OUTLINE,
        DRIVE_FOLDER_UPLOAD,
        FILE_DOWNLOAD,
        FILE_DOWNLOAD_DONE,
        FILE_UPLOAD,
        FOLDER,
        FOLDER_OPEN,
        FOLDER_SHARED,
        GRID_VIEW,
        REQUEST_QUOTE,
        RULE_FOLDER,
        SNIPPET_FOLDER,
        TEXT_SNIPPET,
        TOPIC,
        UPLOAD,
        UPLOAD_FILE,
        WORKSPACES_FILLED,
        WORKSPACES_OUTLINE,
        BROWSER_NOT_SUPPORTED,
        CAST,
        CAST_CONNECTED,
        CAST_FOR_EDUCATION,
        COMPUTER,
        CONNECTED_TV,
        DESKTOP_MAC,
        DESKTOP_WINDOWS,
        DEVELOPER_BOARD,
        DEVICE_HUB,
        DEVICE_UNKNOWN,
        DEVICES_OTHER,
        DOCK,
        GAMEPAD,
        HEADSET,
        HEADSET_MIC,
        HEADSET_OFF,
        KEYBOARD,
        KEYBOARD_ARROW_DOWN,
        KEYBOARD_ARROW_LEFT,
        KEYBOARD_ARROW_RIGHT,
        KEYBOARD_ARROW_UP,
        KEYBOARD_BACKSPACE,
        KEYBOARD_CAPSLOCK,
        KEYBOARD_HIDE,
        KEYBOARD_RETURN,
        KEYBOARD_TAB,
        KEYBOARD_VOICE,
        LAPTOP,
        LAPTOP_CHROMEBOOK,
        LAPTOP_MAC,
        LAPTOP_WINDOWS,
        MEMORY,
        MONITOR,
        MOUSE,
        PHONE_ANDROID,
        PHONE_IPHONE,
        PHONELINK,
        PHONELINK_OFF,
        POINT_OF_SALE,
        POWER_INPUT,
        ROUTER,
        SCANNER,
        SECURITY,
        SIM_CARD,
        SMARTPHONE,
        SPEAKER,
        SPEAKER_GROUP,
        TABLET,
        TABLET_ANDROID,
        TABLET_MAC,
        TOYS,
        TV,
        VIDEOGAME_ASSET,
        WATCH,
        SENSOR_DOOR,
        SENSOR_WINDOW,
        _10MP,
        _11MP,
        _12MP,
        _13MP,
        _14MP,
        _15MP,
        _16MP,
        _17MP,
        _18MP,
        _19MP,
        _20MP,
        _21MP,
        _22MP,
        _23MP,
        _24MP,
        _2MP,
        _3MP,
        _4MP,
        _5MP,
        _6MP,
        _7MP,
        _8MP,
        _9MP,
        ADD_A_PHOTO,
        ADD_PHOTO_ALTERNATE,
        ADD_TO_PHOTOS,
        ADJUST,
        ANIMATION,
        ASSISTANT,
        ASSISTANT_PHOTO,
        AUDIOTRACK,
        AUTO_AWESOME,
        AUTO_AWESOME_MOSAIC,
        AUTO_AWESOME_MOTION,
        AUTO_FIX_HIGH,
        AUTO_FIX_NORMAL,
        AUTO_FIX_OFF,
        AUTO_STORIES,
        BEDTIME,
        BLUR_CIRCULAR,
        BLUR_LINEAR,
        BLUR_OFF,
        BLUR_ON,
        BRIGHTNESS_1,
        BRIGHTNESS_2,
        BRIGHTNESS_3,
        BRIGHTNESS_4,
        BRIGHTNESS_5,
        BRIGHTNESS_6,
        BRIGHTNESS_7,
        BROKEN_IMAGE,
        BRUSH,
        BURST_MODE,
        CAMERA,
        CAMERA_ALT,
        CAMERA_FRONT,
        CAMERA_REAR,
        CAMERA_ROLL,
        CASES,
        CENTER_FOCUS_STRONG,
        CENTER_FOCUS_WEAK,
        CIRCLE,
        COLLECTIONS,
        COLLECTIONS_BOOKMARK,
        COLOR_LENS,
        COLORIZE,
        COMPARE,
        CONTROL_POINT,
        CONTROL_POINT_DUPLICATE,
        CROP,
        CROP_16_9,
        CROP_3_2,
        CROP_5_4,
        CROP_7_5,
        CROP_DIN,
        CROP_FREE,
        CROP_LANDSCAPE,
        CROP_ORIGINAL,
        CROP_PORTRAIT,
        CROP_ROTATE,
        CROP_SQUARE,
        DEHAZE,
        DETAILS,
        DIRTY_LENS,
        EDIT,
        EURO,
        EXPOSURE,
        EXPOSURE_NEG_1,
        EXPOSURE_NEG_2,
        EXPOSURE_PLUS_1,
        EXPOSURE_PLUS_2,
        EXPOSURE_ZERO,
        FACE_RETOUCHING_NATURAL,
        FILTER,
        FILTER_1,
        FILTER_2,
        FILTER_3,
        FILTER_4,
        FILTER_5,
        FILTER_6,
        FILTER_7,
        FILTER_8,
        FILTER_9,
        FILTER_9_PLUS,
        FILTER_B_AND_W,
        FILTER_CENTER_FOCUS,
        FILTER_DRAMA,
        FILTER_FRAMES,
        FILTER_HDR,
        FILTER_NONE,
        FILTER_TILT_SHIFT,
        FILTER_VINTAGE,
        FLARE,
        FLASH_AUTO,
        FLASH_OFF,
        FLASH_ON,
        FLIP,
        FLIP_CAMERA_ANDROID,
        FLIP_CAMERA_IOS,
        GRADIENT,
        GRAIN,
        GRID_OFF,
        GRID_ON,
        HDR_ENHANCED_SELECT,
        HDR_OFF,
        HDR_ON,
        HDR_STRONG,
        HDR_WEAK,
        HEALING,
        IMAGE,
        IMAGE_ASPECT_RATIO,
        IMAGE_NOT_SUPPORTED,
        IMAGE_SEARCH,
        ISO,
        LANDSCAPE,
        LEAK_ADD,
        LEAK_REMOVE,
        LENS,
        LINKED_CAMERA,
        LOOKS,
        LOOKS_3,
        LOOKS_4,
        LOOKS_5,
        LOOKS_6,
        LOOKS_ONE,
        LOOKS_TWO,
        LOUPE,
        MIC_EXTERNAL_OFF,
        MIC_EXTERNAL_ON,
        MONOCHROME_PHOTOS,
        MOTION_PHOTOS_OFF,
        MOTION_PHOTOS_ON,
        MOTION_PHOTOS_PAUSE,
        MOTION_PHOTOS_PAUSED,
        MOVIE_CREATION,
        MOVIE_FILTER,
        MP,
        MUSIC_NOTE,
        MUSIC_OFF,
        NATURE,
        NATURE_PEOPLE,
        NAVIGATE_BEFORE,
        NAVIGATE_NEXT,
        PALETTE,
        PANORAMA,
        PANORAMA_FISH_EYE,
        PANORAMA_HORIZONTAL,
        PANORAMA_HORIZONTAL_SELECT,
        PANORAMA_PHOTOSPHERE,
        PANORAMA_PHOTOSPHERE_SELECT,
        PANORAMA_VERTICAL,
        PANORAMA_VERTICAL_SELECT,
        PANORAMA_WIDE_ANGLE,
        PANORAMA_WIDE_ANGLE_SELECT,
        PHOTO,
        PHOTO_ALBUM,
        PHOTO_CAMERA,
        PHOTO_CAMERA_BACK,
        PHOTO_CAMERA_FRONT,
        PHOTO_FILTER,
        PHOTO_LIBRARY,
        PHOTO_SIZE_SELECT_ACTUAL,
        PHOTO_SIZE_SELECT_LARGE,
        PHOTO_SIZE_SELECT_SMALL,
        PICTURE_AS_PDF,
        PORTRAIT,
        RECEIPT_LONG,
        REMOVE_RED_EYE,
        ROTATE_90_DEGREES_CCW,
        ROTATE_LEFT,
        ROTATE_RIGHT,
        SHUTTER_SPEED,
        SLIDESHOW,
        STRAIGHTEN,
        STYLE,
        TAG_FACES,
        TIMER,
        TIMER_10,
        TIMER_3,
        TONALITY,
        TRANSFORM,
        TUNE,
        VIEW_COMPACT,
        WB_INCANDESCENT,
        SWITCH_CAMERA,
        SWITCH_VIDEO,
        TEXTURE,
        TIMELAPSE,
        TIMER_OFF,
        VIEW_COMFY,
        VIGNETTE,
        WB_AUTO,
        WB_CLOUDY,
        WB_IRIDESCENT,
        WB_SHADE,
        WB_SUNNY,
        WB_TWIGHLIGHT,
        _360,
        ADD_BUSINESS,
        ADD_LOCATION,
        ADD_LOCATION_ALT,
        ADD_ROAD,
        AGRICULTURE,
        ALT_ROUTE,
        ATM,
        ATTRACTIONS,
        BADGE,
        BAKERY_DINING,
        BEENHERE,
        BIKE_SCOOTER,
        BREAKFAST_DINING,
        BRUNCH_DINING,
        BUS_ALERT,
        CAR_RENTAL,
        CAR_REPAIR,
        CATEGORY,
        CELEBRATION,
        CLEANING_SERVICES,
        COMPASS_CALIBRATION,
        DELIVERY_DINING,
        DEPARTURE_BOARD,
        DESIGN_SERVICES,
        DINNER_DINING,
        DIRECTIONS,
        DIRECTIONS_BIKE,
        DIRECTIONS_BOAT,
        DIRECTIONS_BUS,
        DIRECTIONS_CAR,
        DIRECTIONS_RAILWAY,
        DIRECTIONS_RUN,
        DIRECTIONS_SUBWAY,
        DIRECTIONS_TRANSIT,
        DIRECTIONS_WALK,
        DRY_CLEANING,
        EDIT_ATTRIBUTES,
        EDIT_LOCATION,
        EDIT_ROAD,
        ELECTRIC_BIKE,
        ELECTRIC_CAR,
        ELECTRIC_MOPED,
        ELECTRIC_RICKSHAW,
        ELECTRIC_SCOOTER,
        ELECTRICAL_SERVICES,
        EV_STATION,
        FASTFOOD,
        FESTIVAL,
        FLIGHT,
        HAIL,
        HANDYMAN,
        HARDWARE,
        HOME_REPAIR_SERVICE,
        HOTEL,
        HVAC,
        ICECREAM,
        LAYERS,
        LAYERS_CLEAR,
        LIQUOR,
        LOCAL_ACTIVITY,
        LOCAL_AIRPORT,
        LOCAL_ATM,
        LOCAL_BAR,
        LOCAL_CAFE,
        LOCAL_CAR_WASH,
        LOCAL_CONVENIENCE_STORE,
        LOCAL_DINING,
        LOCAL_DRINK,
        LOCAL_FIRE_DEPARTMENT,
        LOCAL_FLORIST,
        LOCAL_GAS_STATION,
        LOCAL_GROCERY_STORE,
        LOCAL_HOSPITAL,
        LOCAL_HOTEL,
        LOCAL_LAUNDRY_SERVICE,
        LOCAL_LIBRARY,
        LOCAL_MALL,
        LOCAL_MOVIES,
        LOCAL_OFFER,
        LOCAL_PARKING,
        LOCAL_PHARMACY,
        LOCAL_PHONE,
        LOCAL_PIZZA,
        LOCAL_PLAY,
        LOCAL_POLICE,
        LOCAL_POST_OFFICE,
        LOCAL_PRINTSHOP,
        LOCAL_SEE,
        LOCAL_SHIPPING,
        LOCAL_TAXI,
        LOCATION_PIN,
        LUNCH_DINING,
        MAP,
        MAPS_UGC,
        MEDICAL_SERVICES,
        MENU_BOOK,
        MISCELLANEOUS_SERVICES,
        MONEY,
        MOPED,
        MULTIPLE_STOP,
        MUSEUM,
        MY_LOCATION,
        NAVIGATION,
        NEAR_ME,
        NEAR_ME_DISABLED,
        NIGHTLIFE,
        NO_MEALS,
        NO_MEALS_OULINE,
        NO_TRANSFER,
        NOT_LISTED_LOCATION,
        PARK,
        PEDAL_BIKE,
        PERSON_PIN,
        PERSON_PIN_CIRCLE,
        PEST_CONTROL,
        PEST_CONTROL_RODENT,
        PIN_DROP,
        PLACE,
        PLUMBING,
        RAILWAY_ALERT,
        RAMEN_DINING,
        RATE_REVIEW,
        RESTAURANT,
        RESTAURANT_MENU,
        RUN_CIRCLE,
        SATELLITE,
        SET_MEAL,
        STORE_MALL_DIRECTORY,
        STREETVIEW,
        SUBWAY,
        TAKEOUT_DINING,
        TAXI_ALERT,
        TERRAIN,
        THEATER_COMEDY,
        TRAFFIC,
        TRAIN,
        TRAM,
        TRANSFER_WITHIN_A_STATION,
        TRANSIT_ENTEREXIT,
        TRIP_ORIGIN,
        TWO_WHEELER,
        VOLUNTEER_ACTIVISM,
        WINE_BAR,
        WRONG_LOCATION,
        ZOOM_OUT_MAP,
        APP_SETTINGS_ALT,
        APPS,
        ARROW_BACK,
        ARROW_BACK_IOS,
        ARROW_DOWNWARD,
        ARROW_DROP_DOWN,
        ARROW_DROP_DOWN_CIRCLE,
        ARROW_DROP_UP,
        ARROW_FORWARD,
        ARROW_FORWARD_IOS,
        ARROW_LEFT,
        ARROW_RIGHT,
        ARROW_UPWARD,
        ASSISTANT_DIRECTION,
        ASSISTANT_NAVIGATION,
        CAMPAIGN,
        CANCEL,
        CHECK,
        CHEVRON_LEFT,
        CHEVRON_RIGHT,
        CLOSE,
        DOUBLE_ARROW,
        EAST,
        EXPAND_LESS,
        EXPAND_MORE,
        FIRST_PAGE,
        FULLSCREEN,
        FULLSCREEN_EXIT,
        HOME_WORK,
        LAST_PAGE,
        LEGEND_TOGGLE,
        MENU,
        MENU_OPEN,
        MORE_HORIZ,
        MORE_VERT,
        NORTH,
        NORTH_EAST,
        NORTH_WEST,
        OFFLINE_SHARE,
        PAYMENTS,
        PIVOT_TABLE_CHART,
        REFRESH,
        SOUTH,
        SOUTH_EAST,
        SOUTH_WEST,
        SUBDIRECTORY_ARROW_LEFT,
        SUBDIRECTORY_ARROW_RIGHT,
        SWITCH_LEFT,
        SWITCH_RIGHT,
        UNFOLD_LESS,
        UNFOLD_MORE,
        WATERFALL_CHART,
        WEST,
        ACCOUNT_TREE,
        ADB,
        ADD_CALL,
        AIRLINE_SEAT_FLAT,
        AIRLINE_SEAT_FLAT_ANGLED,
        AIRLINE_SEAT_INDIVIDUAL_SUITE,
        AIRLINE_SEAT_LEGROOM_EXTRA,
        AIRLINE_SEAT_LEGROOM_NORMAL,
        AIRLINE_SEAT_LEGROOM_REDUCED,
        AIRLINE_SEAT_RECLINE_EXTRA,
        AIRLINE_SEAT_RECLINE_NORMAL,
        BLUETOOTH_AUDIO,
        CONFIRMATION_NUMBER,
        DIRECTIONS_OFF,
        DISC_FULL,
        DO_DISTURB,
        DO_DISTURB_ALT,
        DO_DISTURB_OFF,
        DO_DISTURB_ON,
        DO_NOT_DISTURB,
        DO_NOT_DISTURB_ALT,
        DO_NOT_DISTURB_OFF,
        DO_NOT_DISTURB_ON,
        DRIVE_ETA,
        ENHANCED_ENCRYPTION,
        EVENT_AVAILABLE,
        EVENT_BUSY,
        EVENT_NOTE,
        FOLDER_SPECIAL,
        IMAGESEARCH_ROLLER,
        LIVE_TV,
        MMS,
        MORE,
        NETWORK_CHECK,
        NETWORK_LOCKED,
        NO_ENCRYPTION,
        NO_ENCRYPTION_GMAILERRORRED,
        ONDEMAND_VIDEO,
        PERSONAL_VIDEO,
        PHONE_BLUETOOTH_SPEAKER,
        PHONE_CALLBACK,
        PHONE_FORWARDED,
        PHONE_IN_TALK,
        PHONE_LOCKED,
        PHONE_MISSED,
        PHONE_PAUSED,
        POWER,
        POWER_OFF,
        PRIORITY_HIGH,
        SD_CARD,
        SD_CARD_ALERT,
        SIM_CARD_ALERT,
        SMS,
        SMS_FAILED,
        SUPPORT_AGENT,
        SYNC,
        SYNC_DISABLED,
        SYNC_PROBLEM,
        SYSTEM_UPDATE,
        TAP_AND_PLAY,
        TIME_TO_LEAVE,
        TV_OFF,
        VIBRATION,
        VOICE_CHAT,
        VPN_LOCK,
        WC,
        WIFI,
        WIFI_OFF,
        AC_UNIT,
        AIRPORT_SHUTTLE,
        ALL_INCLUSIVE,
        APARTMENT,
        BABY_CHANGING_STATION,
        BACKPACK,
        BATHTUB,
        BEACH_ACCESS,
        BENTO,
        BUSINESS_CENTER,
        CARPENTER,
        CASINO,
        CHARGING_STATION,
        CHECKROOM,
        CHILD_CARE,
        CHILD_FRIENDLY,
        CORPORATE_FARE,
        COUNTERTOPS,
        DO_NOT_STEP,
        DO_NOT_TOUCH,
        DRY,
        ELEVATOR,
        ESCALATOR,
        ESCALATOR_WARNING,
        FAMILY_RESTROOM,
        FENCE,
        FIRE_EXTINGUISHER,
        FITNESS_CENTER,
        FOOD_BANK,
        FOUNDATION,
        FREE_BREAKFAST,
        GOLF_COURSE,
        GRASS,
        HOT_TUB,
        HOUSE,
        HOUSE_SIDING,
        KITCHEN,
        MEETING_ROOM,
        MICROWAVE,
        NIGHT_SHELTER,
        NO_BACKPACK,
        NO_CELL,
        NO_DRINKS,
        NO_FLASH,
        NO_FOOD,
        NO_MEETING_ROOM,
        NO_PHOTOGRAPHY,
        NO_STROLLER,
        POOL,
        RICE_BOWL,
        ROOFING,
        ROOM_PREFERENCES,
        ROOM_SERVICE,
        RV_HOOKUP,
        SMOKE_FREE,
        SMOKING_ROOMS,
        SOAP,
        SPA,
        SPORTS_BAR,
        STAIRS,
        STOREFRONT,
        STROLLER,
        TAPAS,
        TTY,
        UMBRELLA,
        WASH,
        WATER_DAMAGE,
        WHEELCHAIR_PICKUP,
        _6_FT_APART,
        ADD_MODERATOR,
        ARCHITECTURE,
        CAKE,
        CLEAN_HANDS,
        CONNECT_WITHOUT_CONTACT,
        CONSTRUCTION,
        CORONAVIRUS,
        DECK,
        DOMAIN,
        ELDERLY,
        EMOJI_EMOTIONS,
        EMOJI_EVENTS,
        EMOJI_FLAGS,
        EMOJI_FOOD_BEVERAGE,
        EMOJI_NATURE,
        EMOJI_OBJECTS,
        EMOJI_PEOPLE,
        EMOJI_SYMBOLS,
        EMOJI_TRANSPORTATION,
        ENGINEERING,
        FACEBOOK,
        FIREPLACE,
        FOLLOW_THE_SIGNS,
        GROUP,
        GROUP_ADD,
        GROUPS,
        HISTORY_EDU,
        IOS_SHARE,
        KING_BED,
        LOCATION_CITY,
        LUGGAGE,
        MASKS,
        MILITARY_TECH,
        MOOD,
        MOOD_BAD,
        NIGHTS_STAY,
        NO_LUGGAGE,
        NOTIFICATIONS,
        NOTIFICATIONS_ACTIVE,
        NOTIFICATIONS_NONE,
        NOTIFICATIONS_OFF,
        NOTIFICATIONS_PAUSED,
        OUTDOOR_GRILL,
        PAGES,
        PARTY_MODE,
        PEOPLE,
        PEOPLE_ALT,
        PEOPLE_OUTLINE,
        PERSON,
        PERSON_ADD,
        PERSON_ADD_ALT,
        PERSON_ADD_ALT_1,
        PERSON_OUTLINE,
        PERSON_REMOVE,
        PERSON_REMOVE_ALT_1,
        PLUS_ONE,
        POLL,
        PRECISION_MANUFACTURING,
        PSYCHOLOGY,
        PUBLIC,
        PUBLIC_OFF,
        RECOMMEND,
        REDUCE_CAPACITY,
        REMOVE_MODERATOR,
        SANITIZER,
        SCHOOL,
        SCIENCE,
        SELF_IMPROVEMENT,
        SENTIMENT_DISSATISFIED,
        SENTIMENT_NEUTRAL,
        SENTIMENT_SATISFIED,
        SENTIMENT_VERY_DISSATISFIED,
        SENTIMENT_VERY_SATISFIED,
        SHARE,
        SICK,
        SINGLE_BED,
        SPORTS,
        SPORTS_BASEBALL,
        SPORTS_BASKETBALL,
        SPORTS_CRICKET,
        SPORTS_ESPORTS,
        SPORTS_FOOTBALL,
        SPORTS_GOLF,
        SPORTS_HANDBALL,
        SPORTS_HOCKEY,
        SPORTS_KABADDI,
        SPORTS_MMA,
        SPORTS_MOTORSPORTS,
        SPORTS_RUGBY,
        SPORTS_SOCCER,
        SPORTS_TENNIS,
        SPORTS_VOLLEYBALL,
        SWITCH_ACCOUNT,
        THUMB_DOWN_ALT,
        THUMB_UP_ALT,
        WHATSHOT,
        CHECK_BOX,
        CHECK_BOX_OUTLINE_BLANK,
        INDETERMINATE_CHECK_BOX,
        RADIO_BUTTON_CHECKED,
        RADIO_BUTTON_UNCHECKED,
        STAR,
        STAR_BORDER,
        STAR_BORDER_PURPLE500,
        STAR_HALF,
        STAR_OUTLINE,
        STAR_PURPLE500,
        TOGGLE_OFF,
        TOGGLE_ON;
        

        public final String[] getPath(StyleType styleType){
            AssetManager assetManager = GlobalUtilSetting.getContext().getAssets();
            int targetLine = (this.ordinal() * 5) + (styleType.ordinal() + 1);
            InputStream inputStream = null;
            LineNumberReader reader = null;
            try {
                inputStream = assetManager.open("VectorPath.db");
                reader = new LineNumberReader(new InputStreamReader(inputStream));
                String line;
                while ((line = reader.readLine()) != null) {
                    if (reader.getLineNumber() == targetLine) {
                        break;
                    }
                }
                if(line.equals("null")){
                    throw new NullPointerException("The " + styleType.name() + " type of " + this.name() + " is null");
                }
                int startIndex = line.indexOf('[');
                int endIndex = line.lastIndexOf(']');
                if (startIndex != -1 && endIndex != -1 && startIndex <= endIndex) {
                    String arrayPart = line.substring(startIndex + 1, endIndex);
                    Pattern pattern = Pattern.compile("\"([^\"]*)\"");
                    Matcher matcher = pattern.matcher(arrayPart);
                    List<String> paths = new ArrayList<>();
                    while (matcher.find()) {
                        paths.add(matcher.group(1));
                    }
                    return paths.toArray(new String[paths.size()]);
                }
            } catch (IOException e) {
                LogReceiver.e(e);
            } finally {
                if (reader != null) {
                    try {
                        reader.close();
                    } catch (IOException e) {
                        LogReceiver.e(e);
                    }
                }
                if (inputStream != null) {
                    try {
                        inputStream.close();
                    } catch (IOException e) {
                        LogReceiver.e(e);
                    }
                }
            }
            return null;
        }
    }
}
